import { reg } from '../../engine/registry';
import { guard, hit, reload, skill, spendAmmo } from '../lib';

/**
 * 장비가 주는 기본기. 수치 배열은 장비 강화 단계(0~2)별.
 * 모두 AP 1, 쿨다운 0 (방어구 일부 예외).
 */
reg.skills([
  // ── 맨손 ──
  skill({
    id: 'punch',
    name: '주먹질',
    icon: 'gi:fist',
    school: 'neutral',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'melee',
    target: 'single',
    type: 'blunt',
    tags: ['attack', 'basic'],
    vals: { dmg: 4 },
    desc: '{D:dmg} 타격 피해',
    run: (c, u, t) => void hit(c, u, t),
  }),
  skill({
    id: 'brace',
    name: '웅크리기',
    icon: 'gi:shield',
    school: 'neutral',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'self',
    target: 'self',
    tags: ['block', 'basic'],
    vals: { blk: 4 },
    desc: '방어도 {B:blk}',
    run: (c, u) => void guard(c, u),
  }),

  // ── 무기 ──
  skill({
    id: 'w-saber',
    name: '사브르 베기',
    icon: 'gi:saber-slash',
    school: 'blade',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'melee',
    target: 'single',
    type: 'slash',
    tags: ['attack', 'basic'],
    vals: { dmg: [6, 8, 10] },
    desc: '{D:dmg} 참격 피해',
    run: (c, u, t) => void hit(c, u, t),
  }),
  skill({
    id: 'w-knife',
    name: '사냥칼 찌르기',
    icon: 'gi:bowie-knife',
    school: 'blade',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'melee',
    target: 'single',
    type: 'slash',
    tags: ['attack', 'basic', 'bleed'],
    vals: { dmg: [4, 5, 6], bleed: [1, 2, 2] },
    desc: '{D:dmg} 참격 피해. 체력 피해를 주면 출혈 {bleed}',
    run: (c, u, t) => {
      const ds = hit(c, u, t);
      if (t && !t.dead && ds.some((d) => d.hpLoss > 0)) c.apply(t, 'bleed', u.v('bleed'), c.p);
    },
  }),
  skill({
    id: 'w-hatchet',
    name: '손도끼 내려치기',
    icon: 'gi:wood-axe',
    school: 'blade',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'melee',
    target: 'single',
    type: 'slash',
    tags: ['attack', 'basic'],
    vals: { dmg: [5, 7, 9], bonus: [3, 4, 5] },
    desc: '{D:dmg} 참격 피해. 대상이 출혈 중이면 피해 +{bonus}',
    run: (c, u, t) => {
      const extra = t && (t.st.bleed ?? 0) > 0 ? u.v('bonus') : 0;
      hit(c, u, t, { dmg: u.v('dmg') + extra });
    },
  }),
  skill({
    id: 'w-revolver',
    name: '리볼버 사격',
    icon: 'gi:revolver',
    school: 'firearm',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'ranged',
    target: 'single',
    type: 'pierce',
    tags: ['attack', 'basic', 'ammo', 'gun'],
    vals: { dmg: [7, 9, 11] },
    desc: '탄약 1 소모, {D:dmg} 관통 피해. 탄약이 없으면 쏘지 않고 재장전',
    run: (c, u, t) => {
      if (c.s.ammo <= 0) return reload(c);
      spendAmmo(c, 1);
      hit(c, u, t);
    },
  }),
  skill({
    id: 'w-shotgun',
    name: '산탄 발사',
    icon: 'gi:sawed-off-shotgun',
    school: 'firearm',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'ranged',
    target: 'front',
    type: 'pierce',
    tags: ['attack', 'basic', 'ammo', 'gun', 'multi'],
    vals: { dmg: [3, 4, 5], hits: 2 },
    desc: '탄약 1 소모, 전열의 모든 적에게 {D:dmg} 관통 피해 {hits}회. 탄약이 없으면 쏘지 않고 재장전',
    run: (c, u, t) => {
      if (c.s.ammo <= 0) return reload(c);
      spendAmmo(c, 1);
      hit(c, u, t);
    },
  }),
  skill({
    id: 'w-harpoon',
    name: '작살 발사',
    icon: 'gi:harpoon-trident',
    school: 'firearm',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'ranged',
    target: 'single',
    type: 'pierce',
    tags: ['attack', 'basic', 'pull'],
    vals: { dmg: [6, 8, 10] },
    desc: '{D:dmg} 관통 피해. 대상이 후열에 있으면 전열로 끌어당긴다 (전열에 자리가 있을 때)',
    run: (c, u, t) => {
      hit(c, u, t);
      if (t && !t.dead && t.row === 1) c.moveRow(t, 0);
    },
  }),
  skill({
    id: 'w-cane',
    name: '지팡이 타격',
    icon: 'gi:wizard-staff',
    school: 'resolve',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'melee',
    target: 'single',
    type: 'blunt',
    tags: ['attack', 'basic'],
    vals: { dmg: [5, 7, 9], poise: 1 },
    desc: '{D:dmg} 타격 피해. 버팀 추가 -{poise}',
    run: (c, u, t) => void hit(c, u, t),
  }),
  skill({
    id: 'w-crowbar',
    name: '쇠지렛대 휘두르기',
    icon: 'gi:crowbar',
    school: 'resolve',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'melee',
    target: 'single',
    type: 'blunt',
    tags: ['attack', 'basic'],
    vals: { dmg: [7, 9, 11] },
    desc: '{D:dmg} 타격 피해',
    run: (c, u, t) => void hit(c, u, t),
  }),
  skill({
    id: 'w-athame',
    name: '인장 새기기',
    icon: 'gi:sacrificial-dagger',
    school: 'occult',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'melee',
    target: 'single',
    type: 'arcane',
    tags: ['attack', 'basic', 'mark'],
    vals: { dmg: [5, 6, 7], mark: [1, 1, 2] },
    desc: '{D:dmg} 비전 피해, 인장 {mark}',
    run: (c, u, t) => {
      hit(c, u, t);
      if (t && !t.dead) c.apply(t, 'mark', u.v('mark'), c.p);
    },
  }),
  skill({
    id: 'w-torch',
    name: '횃불 지지기',
    icon: 'gi:torch',
    school: 'alchemy',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'melee',
    target: 'single',
    type: 'fire',
    tags: ['attack', 'basic', 'burn'],
    vals: { dmg: [4, 5, 6], burn: [2, 2, 3] },
    desc: '{D:dmg} 화염 피해, 화상 {burn}',
    run: (c, u, t) => {
      hit(c, u, t);
      if (t && !t.dead) c.apply(t, 'burn', u.v('burn'), c.p);
    },
  }),
  skill({
    id: 'w-tome',
    name: '금서 낭독',
    icon: 'gi:evil-book',
    school: 'forbidden',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'ranged',
    target: 'single',
    type: 'void',
    tags: ['attack', 'basic', 'insight'],
    vals: { dmg: [4, 5, 6], per: 2 },
    desc: '정신력 1 소모, {D:dmg}+통찰×{per} 공허 피해',
    run: (c, u, t) => {
      c.loseSanity(1);
      hit(c, u, t, { dmg: u.v('dmg') + u.v('per') * c.p.insight });
    },
  }),

  // ── 방어구 ──
  skill({
    id: 'a-coat',
    name: '코트 깃 세우기',
    icon: 'gi:trench-body-armor',
    school: 'neutral',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'self',
    target: 'self',
    tags: ['block', 'basic'],
    vals: { blk: [5, 7, 9] },
    desc: '방어도 {B:blk}',
    run: (c, u) => void guard(c, u),
  }),
  skill({
    id: 'a-leather',
    name: '가죽 갑옷 방어',
    icon: 'gi:leather-armor',
    school: 'neutral',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'self',
    target: 'self',
    tags: ['block', 'basic'],
    vals: { blk: [6, 8, 10] },
    desc: '방어도 {B:blk}',
    run: (c, u) => void guard(c, u),
  }),
  skill({
    id: 'a-robe',
    name: '기도하는 자세',
    icon: 'gi:robe',
    school: 'resolve',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'self',
    target: 'self',
    tags: ['block', 'basic', 'sanity'],
    vals: { blk: [4, 6, 8], san: [1, 2, 2] },
    desc: '방어도 {B:blk}, 정신력 +{san}',
    run: (c, u) => {
      guard(c, u);
      c.gainSanity(u.v('san'));
    },
  }),
  skill({
    id: 'a-chain',
    name: '사슬 조끼 버티기',
    icon: 'gi:chain-mail',
    school: 'resolve',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'self',
    target: 'self',
    tags: ['block', 'basic'],
    vals: { blk: [5, 6, 8], thorns: [2, 3, 3] },
    desc: '방어도 {B:blk}, 반격 {thorns} (다음 내 턴까지)',
    run: (c, u) => {
      guard(c, u);
      c.apply(c.p, 'counter', u.v('thorns'), c.p);
    },
  }),
  skill({
    id: 'a-cloak',
    name: '그림자 망토',
    icon: 'gi:cloak',
    school: 'neutral',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 2,
    range: 'self',
    target: 'self',
    tags: ['block', 'basic'],
    vals: { blk: [3, 4, 6] },
    desc: '방어도 {B:blk}, 회피 1 (재사용 2턴)',
    run: (c, u) => {
      guard(c, u);
      c.apply(c.p, 'evasive', 1, c.p);
    },
  }),
  skill({
    id: 'a-diving',
    name: '잠수복 밀폐',
    icon: 'gi:diving-helmet',
    school: 'neutral',
    rarity: 'basic',
    pool: false,
    cost: 1,
    cd: 0,
    range: 'self',
    target: 'self',
    tags: ['block', 'basic'],
    vals: { blk: [8, 10, 12] },
    desc: '방어도 {B:blk}',
    run: (c, u) => void guard(c, u),
  }),
]);
