import { reg } from '../../engine/registry';
import { combo, guard, hit, skill } from '../lib';

/** 검술 — 출혈과 연계 */
reg.skills([
  skill({
    id: 'quick-cut',
    name: '연속 베기',
    icon: 'gi:crossed-slashes',
    school: 'blade',
    rarity: 'common',
    cost: 1,
    cd: 1,
    range: 'melee',
    target: 'single',
    type: 'slash',
    tags: ['attack', 'combo', 'multi'],
    vals: { dmg: [4, 5], hits: 2 },
    desc: '{D:dmg} 참격 피해 {hits}회. 이번 턴 앞서 스킬을 2개 이상 썼으면 1회 추가',
    run: (c, u, t) => void hit(c, u, t, { hits: u.v('hits') + (combo(c) >= 2 ? 1 : 0) }),
  }),
  skill({
    id: 'serrate',
    name: '톱날 베기',
    icon: 'gi:serrated-slash',
    school: 'blade',
    rarity: 'common',
    cost: 1,
    cd: 1,
    range: 'melee',
    target: 'single',
    type: 'slash',
    tags: ['attack', 'bleed'],
    vals: { dmg: [5, 6], bleed: [3, 5] },
    desc: '{D:dmg} 참격 피해, 출혈 {bleed}',
    run: (c, u, t) => {
      hit(c, u, t);
      if (t && !t.dead) c.apply(t, 'bleed', u.v('bleed'), c.p);
    },
  }),
  skill({
    id: 'lunge',
    name: '찌르고 빠지기',
    icon: 'gi:sword-brandish',
    school: 'blade',
    rarity: 'common',
    cost: 1,
    cd: 1,
    range: 'melee',
    target: 'single',
    type: 'slash',
    tags: ['attack', 'block'],
    vals: { dmg: [8, 10], blk: [4, 6] },
    desc: '{D:dmg} 참격 피해, 방어도 {B:blk}',
    run: (c, u, t) => {
      hit(c, u, t);
      guard(c, u);
    },
  }),
  skill({
    id: 'finisher',
    name: '마무리 일격',
    icon: 'gi:bloody-sword',
    school: 'blade',
    rarity: 'uncommon',
    cost: 2,
    cd: 2,
    range: 'melee',
    target: 'single',
    type: 'slash',
    tags: ['attack', 'combo'],
    vals: { dmg: [11, 13], per: [4, 5] },
    desc: '{D:dmg} 참격 피해. 이번 턴 앞서 사용한 스킬 1개당 +{per}',
    // 연계 추가 피해도 위력(메아리·절약 각인)을 따른다
    run: (c, u, t) => void hit(c, u, t, { dmg: u.v('dmg') + Math.floor(u.v('per') * combo(c) * u.power) }),
  }),
  skill({
    id: 'hemorrhage',
    name: '혈류 폭발',
    icon: 'gi:bleeding-wound',
    school: 'blade',
    rarity: 'uncommon',
    cost: 1,
    cd: 3,
    range: 'melee',
    target: 'single',
    type: 'slash',
    tags: ['attack', 'bleed'],
    vals: { mul: [2, 3] },
    desc: '대상의 출혈 × {mul} 참격 피해 (출혈은 남는다)',
    run: (c, u, t) => {
      const b = t?.st.bleed ?? 0;
      if (b > 0) hit(c, u, t, { dmg: Math.floor(b * u.v('mul') * u.power) });
      else c.emit({ t: 'text', uid: t?.uid, text: '출혈 없음', tone: 'info' });
    },
  }),
  skill({
    id: 'whirlwind',
    name: '회전 베기',
    icon: 'gi:spinning-sword',
    school: 'blade',
    rarity: 'uncommon',
    cost: 2,
    cd: 2,
    range: 'melee',
    target: 'front',
    type: 'slash',
    tags: ['attack', 'aoe', 'bleed'],
    vals: { dmg: [7, 9], bleed: [1, 2] },
    desc: '전열 전체에 {D:dmg} 참격 피해, 출혈 {bleed}',
    run: (c, u, t) => {
      const hitUnits = new Set(hit(c, u, t).map((d) => d.tgt));
      for (const e of hitUnits) if (e.hp > 0) c.apply(e, 'bleed', u.v('bleed'), c.p);
    },
  }),
  skill({
    id: 'flurry',
    name: '칼날 폭풍',
    icon: 'gi:sword-spin',
    school: 'blade',
    rarity: 'rare',
    cost: 1,
    cd: 3,
    range: 'melee',
    target: 'random',
    type: 'slash',
    tags: ['attack', 'combo', 'multi'],
    vals: { dmg: [3, 4], hits: 3 },
    desc: '{D:dmg} 참격 피해 {hits}회, 매번 전열의 무작위 적에게. 이번 턴 앞서 쓴 스킬 1개당 1회 추가',
    run: (c, u, t) => void hit(c, u, t, { hits: u.v('hits') + combo(c) }),
  }),
  skill({
    id: 'riposte',
    name: '흘려치기',
    icon: 'gi:sword-clash',
    school: 'blade',
    rarity: 'uncommon',
    cost: 1,
    cd: 2,
    range: 'self',
    target: 'self',
    tags: ['block', 'counter'],
    vals: { blk: [6, 8], counter: [5, 7] },
    desc: '방어도 {B:blk}, 반격 {counter} (다음 내 턴까지)',
    run: (c, u) => {
      guard(c, u);
      c.apply(c.p, 'counter', u.v('counter'), c.p);
    },
  }),
  skill({
    id: 'blood-dance',
    name: '피의 춤',
    icon: 'gi:dervish-swords',
    school: 'blade',
    rarity: 'rare',
    cost: 0,
    cd: 4,
    range: 'self',
    target: 'self',
    tags: ['buff'],
    vals: { pct: [30, 50] },
    desc: '이번 턴 공격 피해 +{pct}%',
    run: (c, u) => void c.apply(c.p, 'frenzy', u.v('pct'), c.p),
  }),
]);
