import { reg } from '../../engine/registry';
import { detonate, hit, skill } from '../lib';

/** 비술 — 인장 부여와 폭발, 의식 */
reg.skills([
  skill({
    id: 'sigil',
    name: '인장 각인',
    icon: 'gi:pentagram-rose',
    school: 'occult',
    rarity: 'common',
    cost: 1,
    cd: 1,
    range: 'ranged',
    target: 'single',
    type: 'arcane',
    tags: ['attack', 'mark'],
    vals: { dmg: [3, 4], mark: [2, 3] },
    desc: '{D:dmg} 비전 피해, 인장 {mark}',
    run: (c, u, t) => {
      hit(c, u, t);
      if (t && !t.dead) c.apply(t, 'mark', u.v('mark'), c.p);
    },
  }),
  skill({
    id: 'detonate',
    name: '인장 폭발',
    icon: 'gi:explosion-rays',
    school: 'occult',
    rarity: 'common',
    cost: 1,
    cd: 2,
    range: 'ranged',
    target: 'single',
    type: 'arcane',
    tags: ['attack', 'mark', 'detonate'],
    vals: { base: [5, 7], per: [5, 7] },
    desc: '인장을 모두 터뜨려 {base} + 인장당 {per} 비전 피해',
    run: (c, u, t) => {
      if (t) detonate(c, u, t, u.v('per'), u.v('base'));
    },
  }),
  skill({
    id: 'arcane-bolt',
    name: '비전 화살',
    icon: 'gi:magic-swirl',
    school: 'occult',
    rarity: 'common',
    cost: 1,
    cd: 1,
    range: 'ranged',
    target: 'single',
    type: 'arcane',
    tags: ['attack'],
    vals: { dmg: [7, 10] },
    desc: '{D:dmg} 비전 피해',
    run: (c, u, t) => void hit(c, u, t),
  }),
  skill({
    id: 'circle',
    name: '보호의 원',
    icon: 'gi:magic-shield',
    school: 'occult',
    rarity: 'common',
    cost: 1,
    cd: 2,
    range: 'self',
    target: 'self',
    tags: ['barrier'],
    vals: { barrier: [7, 10] },
    desc: '보호막 {barrier} (턴이 지나도 유지)',
    run: (c, u) => void c.apply(c.p, 'barrier', u.v('barrier'), c.p),
  }),
  skill({
    id: 'chant',
    name: '영창',
    icon: 'gi:pentacle',
    school: 'occult',
    rarity: 'uncommon',
    cost: [1, 0],
    cd: 99,
    range: 'self',
    target: 'self',
    tags: ['buff', 'ritual'],
    vals: { n: 1 },
    desc: '의식 {n}: 매 턴 종료 시 힘 +{n}. 전투당 1회',
    run: (c, u) => void c.apply(c.p, 'ritual', u.v('n'), c.p),
  }),
  skill({
    id: 'chain-sigil',
    name: '연쇄 인장',
    icon: 'gi:linked-rings',
    school: 'occult',
    rarity: 'uncommon',
    cost: 1,
    cd: 2,
    range: 'ranged',
    target: 'all',
    type: 'arcane',
    tags: ['attack', 'mark', 'aoe'],
    vals: { dmg: 2, mark: [1, 2] },
    desc: '적 전체에 {D:dmg} 비전 피해, 인장 {mark}',
    run: (c, u, t) => {
      hit(c, u, t);
      for (const e of c.alive) c.apply(e, 'mark', u.v('mark'), c.p);
    },
  }),
  skill({
    id: 'ritual-burst',
    name: '대폭발 의식',
    icon: 'gi:star-swirl',
    school: 'occult',
    rarity: 'rare',
    cost: 2,
    cd: 3,
    range: 'ranged',
    target: 'all',
    type: 'arcane',
    tags: ['attack', 'mark', 'detonate', 'aoe'],
    vals: { per: [6, 8] },
    desc: '모든 적의 인장을 터뜨려 인장당 {per} 비전 피해',
    run: (c, u) => {
      for (const e of [...c.alive]) detonate(c, u, e, u.v('per'));
    },
  }),
  skill({
    id: 'hex',
    name: '저주',
    icon: 'gi:cursed-star',
    school: 'occult',
    rarity: 'uncommon',
    cost: 1,
    cd: 2,
    range: 'ranged',
    target: 'single',
    tags: ['debuff'],
    vals: { weak: 2, vuln: [1, 2] },
    desc: '약화 {weak}, 취약 {vuln}',
    run: (c, u, t) => {
      if (!t) return;
      c.apply(t, 'weak', u.v('weak'), c.p);
      c.apply(t, 'vuln', u.v('vuln'), c.p);
    },
  }),
]);
