import { reg } from '../../engine/registry';
import { guard, hit, skill } from '../lib';

/** 결의 — 방어, 반격, 정신력 */
reg.skills([
  skill({
    id: 'shield-bash',
    name: '방패 강타',
    icon: 'gi:shield-bash',
    school: 'resolve',
    rarity: 'common',
    cost: 1,
    cd: 1,
    range: 'melee',
    target: 'single',
    type: 'blunt',
    tags: ['attack', 'block'],
    makes: [],
    reads: ['block'],
    vals: { dmg: [6, 7], pct: [50, 75] },
    desc: '{D:dmg} + 현재 방어도의 {pct}% 타격 피해',
    // 방어도 비례 피해도 위력(메아리·절약 각인)을 따른다
    run: (c, u, t) => void hit(c, u, t, { dmg: u.v('dmg') + Math.floor((c.p.block * u.v('pct') * u.power) / 100) }),
  }),
  skill({
    id: 'steady',
    name: '마음 다잡기',
    icon: 'gi:meditation',
    school: 'resolve',
    rarity: 'common',
    cost: 1,
    cd: 2,
    range: 'self',
    target: 'self',
    tags: ['block', 'sanity'],
    makes: ['block'],
    reads: [],
    vals: { blk: [6, 8], san: [3, 4] },
    desc: '방어도 {B:blk}, 정신력 +{san}',
    run: (c, u) => {
      guard(c, u);
      c.gainSanity(u.v('san'));
    },
  }),
  skill({
    id: 'iron-will',
    name: '강철 의지',
    icon: 'gi:stone-wall',
    school: 'resolve',
    rarity: 'uncommon',
    cost: 1,
    cd: 3,
    range: 'self',
    target: 'self',
    tags: ['block', 'retain'],
    makes: ['block'],
    reads: [],
    vals: { blk: [5, 8], turns: 2 },
    desc: '방어도 {B:blk}. {turns}턴 동안 방어도 유지',
    run: (c, u) => {
      guard(c, u);
      c.apply(c.p, 'retain', u.v('turns'), c.p);
    },
  }),
  skill({
    id: 'taunt',
    name: '도발의 함성',
    icon: 'gi:shouting',
    school: 'resolve',
    rarity: 'common',
    cost: 1,
    cd: 2,
    range: 'self',
    target: 'self',
    tags: ['block', 'counter'],
    makes: ['block', 'counter'],
    reads: [],
    vals: { blk: [7, 10], counter: [3, 4] },
    desc: '방어도 {B:blk}, 반격 {counter} (다음 내 턴까지)',
    run: (c, u) => {
      guard(c, u);
      c.apply(c.p, 'counter', u.v('counter'), c.p);
    },
  }),
  skill({
    id: 'bulwark',
    name: '보루',
    icon: 'gi:shield-reflect',
    school: 'resolve',
    rarity: 'uncommon',
    cost: 2,
    cd: 3,
    range: 'self',
    target: 'self',
    tags: ['block'],
    makes: ['block'],
    reads: [],
    vals: { blk: [16, 22] },
    desc: '방어도 {B:blk}',
    run: (c, u) => void guard(c, u),
  }),
  skill({
    id: 'last-stand',
    name: '최후의 저항',
    icon: 'gi:broken-shield',
    school: 'resolve',
    rarity: 'rare',
    cost: 1,
    cd: 4,
    range: 'self',
    target: 'self',
    tags: ['block'],
    makes: ['block'],
    reads: [],
    vals: { pct: [35, 50] },
    desc: '잃은 체력의 {pct}%만큼 방어도',
    run: (c, u) => void guard(c, u, Math.floor(((c.p.maxHp - c.p.hp) * u.v('pct') * u.power) / 100)),
  }),
  skill({
    id: 'rally',
    name: '투지',
    icon: 'gi:biceps',
    school: 'resolve',
    rarity: 'uncommon',
    cost: 0,
    cd: [3, 2],
    range: 'self',
    target: 'self',
    tags: ['buff', 'sanity'],
    makes: [],
    reads: [],
    vals: { str: 1, san: 2 },
    desc: '힘 +{str} (전투 동안), 정신력 +{san}',
    run: (c, u) => {
      c.apply(c.p, 'str', u.v('str'), c.p);
      c.gainSanity(u.v('san'));
    },
  }),
  skill({
    id: 'body-slam',
    name: '몸통 박치기',
    icon: 'gi:shoulder-armor',
    school: 'resolve',
    rarity: 'rare',
    cost: 1,
    cd: 2,
    range: 'melee',
    target: 'single',
    type: 'blunt',
    tags: ['attack', 'block'],
    makes: [],
    reads: ['block'],
    vals: { poise: [0, 1] },
    desc: '현재 방어도만큼 타격 피해. 버팀 추가 -{poise}',
    run: (c, u, t) => void hit(c, u, t, { dmg: Math.floor(c.p.block * u.power) }),
  }),
]);
