import { reg } from '../engine/registry';

reg.origins([
  {
    id: 'soldier',
    name: '퇴역 군인',
    icon: 'gi:rank-3',
    desc: '전쟁이 끝난 뒤에도 총을 놓지 못했다. 사격과 결의로 버틴다.',
    hp: 76,
    sanity: 90,
    gold: 60,
    skills: ['aimed-shot', 'reload', 'shield-bash', 'steady'],
    equip: { weapon: 'revolver', armor: 'coat', trinket1: 'bandolier' },
    consumables: ['bandage'],
    schools: ['firearm', 'resolve'],
  },
  {
    id: 'hunter',
    name: '밤 사냥꾼',
    icon: 'gi:hunter-eyes',
    desc: '안개 속 짐승을 쫓아 살아왔다. 칼과 약품을 다룬다.',
    hp: 76,
    sanity: 95,
    gold: 50,
    skills: ['serrate', 'quick-cut', 'fire-flask', 'smoke-veil'],
    equip: { weapon: 'knife', armor: 'leather', trinket1: 'whetstone' },
    consumables: ['molotov'],
    schools: ['blade', 'alchemy'],
    unlock: '2층에 도달하면 해금',
  },
  {
    id: 'occultist',
    name: '오컬트 학자',
    icon: 'gi:spell-book',
    desc: '금지된 책을 너무 많이 읽었다. 인장과 금기의 지식을 쓴다.',
    hp: 72,
    sanity: 110,
    gold: 70,
    skills: ['sigil', 'detonate', 'circle', 'whisper-void'],
    equip: { weapon: 'athame', armor: 'robe', trinket1: 'occult-ring' },
    consumables: ['laudanum'],
    relics: ['old-bible'],
    schools: ['occult', 'forbidden'],
    unlock: '3층에 도달하면 해금',
  },
]);
